icon_spinner_still = I(_class='fa', _style="display:none")
icon_add = I(_class='fa fa-plus')
icon_primary_paper = I(_class='fa fa-check-circle-o')
icon_all_paper = I(_class='fa fa-circle-o')
icon_pick_review = SPAN(I(_class='fa fa-align-right'), I(_class='fa fa-align-left'))
icon_empty = I(_class='fa fa-circle-o hidden')
icon_edit = I(_class='fa fa-pencil-square-o')
icon_reviews = I(_class='fa fa-balance-scale')
icon_view = I(_class='fa fa-eye')
icon_details = I(_class='fa fa-info')
icon_your_review = icon_view
icon_delete = I(_class='fa fa-trash-o')
icon_hide = I(_class='fa fa-eye-slash')
icon_cancel = I(_class = 'fa fa-times')
